### ISSUE TITLE
[BUG] windowSize argument in moving* function class should be mandatory

### ISSUE THREAD

**Issue by Secathor** [go-graphite/carbonapi#537]
**Describe the bug**

carbonapi 0.14.1-1 from deb package

Bug occurs after big query is run, instantly.

**Logs**

curl to carbonapi:

```
Internal Server Error: runtime error: index out of range [60] with length 60
Stack trace: github.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler.func2
	/root/go/src/github.com/go-graphite/carbonapi/cmd/carbonapi/http/render_handler.go:238
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:975
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:88
github.com/go-graphite/carbonapi/expr/functions/diffSeries.(*diffSeries).Do
	/root/go/src/github.com/go-graphite/carbonapi/expr/functions/diffSeries/function.go:80
github.com/go-graphite/carbonapi/expr.EvalExpr
	/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:148
github.com/go-graphite/carbonapi/expr.evaluator.Eval
	/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:114
github.com/go-graphite/carbonapi/expr.evaluator.FetchAndEvalExp
	/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:91
github.com/go-graphite/carbonapi/expr.FetchAndEvalExp
	/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:126
github.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler
	/root/go/src/github.com/go-graphite/carbonapi/cmd/carbonapi/http/render_handler.go:267
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
github.com/go-graphite/carbonapi/util/ctx.ParseCtx.func1
	/root/go/src/github.com/go-graphite/carbonapi/util/ctx/ctx.go:90
github.com/go-graphite/carbonapi/cmd/carbonapi/http.enrichContextWithHeaders.func1
	/root/go/src/github.com/go-graphite/carbonapi/cmd/carbonapi/http/enrichcontext.go:32
github.com/dgryski/httputil.TimeHandler.func1
	/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/dgryski/httputil/times.go:26
github.com/dgryski/httputil.TrackConnections.func1
	/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/dgryski/httputil/track.go:40
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2417
github.com/gorilla/handlers.CompressHandlerLevel.func1
	/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/compress.go:148
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
github.com/gorilla/handlers.(*cors).ServeHTTP
	/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/cors.go:54
github.com/gorilla/handlers.ProxyHeaders.func1
	/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/proxy_headers.go:59
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2042
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2843
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1925
```

Debug log:

```
2020-10-27T16:30:09.707+0100    ERROR   render  panic during eval:      {"carbonapi_uuid": "c4a7b21b-a835-4fdd-8a6d-b5469e55d9bc", "username": "", "request_headers": {}, "cache_key": "format=json&from=-1h&tar
get=diffSeries%28transformNull%28diffSeries%28sumSeries%28metric.path.and.name.cut%29%2C+movingAverage%28sumSeries%28metric.path.and.name.cut%29%2C+%221h%22%29%29%2C+0%29%2C+movingMax%28movingAverage%28transformNull%28removeBelowValue%28sumSeries%28metric_cut%29%2C+0.5%29%2C+0.5%29%2C+%2224h%22%29%2C+%2224h%22%29%29", "reason": "runtime error: index out of range [60] with length 60", "stack": "github.com/go-graphite/carbonapi/cmd/carbo
napi/http.renderHandler.func2\n\t/root/go/src/github.com/go-graphite/carbonapi/cmd/carbonapi/http/render_handler.go:233\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:975\nruntime.goPanicIndex\n\t/usr
/local/go/src/runtime/panic.go:88\ngithub.com/go-graphite/carbonapi/expr/functions/diffSeries.(*diffSeries).Do\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/functions/diffSeries/function.go:80\ngithub
.com/go-graphite/carbonapi/expr.EvalExpr\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:148\ngithub.com/go-graphite/carbonapi/expr.evaluator.Eval\n\t/root/go/src/github.com/go-graphite/carbonap
i/expr/expr.go:114\ngithub.com/go-graphite/carbonapi/expr.evaluator.FetchAndEvalExp\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:91\ngithub.com/go-graphite/carbonapi/expr.FetchAndEvalExp\n\t/
root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:126\ngithub.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler\n\t/root/go/src/github.com/go-graphite/carbonapi/cmd/carbonapi/http/render_hand
ler.go:267\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\ngithub.com/go-graphite/carbonapi/util/ctx.ParseCtx.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/util/ctx/ctx.
go:90\ngithub.com/go-graphite/carbonapi/cmd/carbonapi/http.enrichContextWithHeaders.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/cmd/carbonapi/http/enrichcontext.go:32\ngithub.com/dgryski/httputil.T
imeHandler.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/dgryski/httputil/times.go:26\ngithub.com/dgryski/httputil.TrackConnections.func1\n\t/root/go/src/github.com/go-graphite/carb
onapi/vendor/github.com/dgryski/httputil/track.go:40\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2417\n
github.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/compress.go:148\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/
net/http/server.go:2042\ngithub.com/gorilla/handlers.(*cors).ServeHTTP\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/cors.go:54\ngithub.com/gorilla/handlers.ProxyHeaders.
func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/proxy_headers.go:59\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\nnet/http.serverHandl
er.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1925"}
2020-10-27T16:30:09.707+0100    ERROR   access  request failed  {"data": {"handler":"render","carbonapi_uuid":"c4a7b21b-a835-4fdd-8a6d-b5469e55d9bc","url":"/render?target=diffSeries(transformNull(diffSeries(s
umSeries(metric.path.and.name.cut),+movingAverage(sumSeries(metric.path.and.name.cut),+%221h%22)),
+0),+movingMax(movingAverage(transformNull(removeBelowValue(sumSeries(metric.path.and.name.cut),+0.5),+0.5),+%2224h%22),+%2224h%22))&from=-1h&format=json
","peer_ip":"127.0.0.1","peer_port":"56536","host":"carbonapi","format":"json","use_cache":true,"targets":["diffSeries(transformNull(diffSeries(sumSeries(metric.path.and.name.cut), movingAverage(sumSeries(metric.path.and.name.cut), \"1h\")), 0), movingMax(movingAverage(transformNull(removeBelowValue(sumSe
ries(metric.path.and.name.cut), 0.5), 0.5), \"24h\"), \"24h\"))"],"cache_timeout":60,"runtime":0.404412661,"http_code":500,"reason":"runtime error: index
 out of range [60] with length 60\nStack trace: github.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler.func2\n\t/root/go/src/github.com/go-graphite/carbonapi/cmd/carbonapi/http/render_handler.go:23
8\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:975\nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:88\ngithub.com/go-graphite/carbonapi/expr/functions/diffSeries.(*diffSeries).Do\n\t/roo
t/go/src/github.com/go-graphite/carbonapi/expr/functions/diffSeries/function.go:80\ngithub.com/go-graphite/carbonapi/expr.EvalExpr\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:148\ngithub.com
/go-graphite/carbonapi/expr.evaluator.Eval\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:114\ngithub.com/go-graphite/carbonapi/expr.evaluator.FetchAndEvalExp\n\t/root/go/src/github.com/go-grap
hite/carbonapi/expr/expr.go:91\ngithub.com/go-graphite/carbonapi/expr.FetchAndEvalExp\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:126\ngithub.com/go-graphite/carbonapi/cmd/carbonapi/http.ren
derHandler\n\t/root/go/src/github.com/go-graphite/carbonapi/cmd/carbonapi/http/render_handler.go:267\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\ngithub.com/go-graphite/carbon
api/util/ctx.ParseCtx.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/util/ctx/ctx.go:90\ngithub.com/go-graphite/carbonapi/cmd/carbonapi/http.enrichContextWithHeaders.func1\n\t/root/go/src/github.com/g
o-graphite/carbonapi/cmd/carbonapi/http/enrichcontext.go:32\ngithub.com/dgryski/httputil.TimeHandler.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/dgryski/httputil/times.go:26\ngith
ub.com/dgryski/httputil.TrackConnections.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/dgryski/httputil/track.go:40\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/ser
ver.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2417\ngithub.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.
com/gorilla/handlers/compress.go:148\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\ngithub.com/gorilla/handlers.(*cors).ServeHTTP\n\t/root/go/src/github.com/go-graphite/carbonap
i/vendor/github.com/gorilla/handlers/cors.go:54\ngithub.com/gorilla/handlers.ProxyHeaders.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/proxy_headers.go:59\nnet/htt
p.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server
.go:1925","from":1603809009,"until":1603812609,"from_raw":"-1h","uri":"/render?target=diffSeries(transformNull(diffSeries(sumSeries(metric.path.and.name.cut),+movingAverage(sumSeries(metric.path.and.name.cut),+%221h%22)),+0),+movingMax(movingAverage(transformNull(removeBelowValue(sumSeries(metric.path.and.name.cut),+0.5),+0.5),+%2224h%22),+%2224h%22))&from=-1h&format=json","from_cache":false,"used_backend_cache":false,"request_headers":{}}}
```

**CarbonAPI Configuration:**

```
# Need to be URL, http or https
# This url specifies the backend or a loadbalancer
#
# Is you are using carbonzipper you should set it to
# zipper's url
#
# If you are using plain go-carbon or graphite-clickhouse
# you should set it to URL of go-carbon's carbonserver module
# or graphite-clickhouse's http url.
# Listen address, should always include hostname or ip address and a port.
listen: ":8081"
# Max concurrent requests to CarbonZipper
concurency: 1000
cache:
   # Type of caching. Valid: "mem", "memcache", "null"
   type: "mem"
   # Cache limit in megabytes
   size_mb: 0
   # Default cache timeout value. Identical to DEFAULT_CACHE_DURATION in graphite-web.
   defaultTimeoutSec: 60
   # Only used by memcache type of cache. List of memcache servers.
   memcachedServers:
       - "127.0.0.1:1234"
       - "127.0.0.2:1235"
# Amount of CPUs to use. 0 - unlimited
cpus: 8
# Timezone, default - local
tz: ""
# If 'true', carbonapi will send requests as is, with globs and braces
# Otherwise for each request it will generate /metrics/find and then /render
# individual metrics.
# true --- faster, but will cause carbonzipper to consume much more RAM.
#
# For some backends (e.x. graphite-clickhouse) this *MUST* be set to true in order
# to get reasonable performance
#
# For go-carbon --- it depends on how you use it.
sendGlobsAsIs: true
# If sendGlobsAsIs is set and resulting response will be larger than maxBatchSize
# carbonapi will revert to old behavir. This allows you to use benifits of passing
# globs as is but keep memory usage in sane limits.
#
# For go-carbon you might want it to keep in some reasonable limits, 100 is good "safe" defaults
#
# For some backends (e.x. graphite-clickhouse) you might want to set it to some insanly high value, like 100000

# If 'true', carbonapi will send requests as is, with globs and braces
# even without checking maxBatchSize
# in result it can increase performance for graphite-clickhouse by removing /metric/find request before calling /render
alwaysSendGlobsAsIs: true

#This option controls what status code will be returned if /render or /metrics/find won't return any metrics
#In some cases someone would like to override this to "200".
# Example use case - when you create a dashboard before service starts to send any data out and don't want to have errors from Grafana.
notFoundStatusCode: 200

functionsConfigs:
    graphiteWeb: /etc/graphiteWeb.example.yaml
maxBatchSize: 100000000
graphite:
    # Host:port where to send internal metrics
    # Empty = disabled
    host: ""
    interval: "60s"
    prefix: "carbon.api"
    # rules on how to construct metric name. For now only {prefix} and {fqdn} is supported.
    # {prefix} will be replaced with the content of {prefix}
    # {fqdn} will be repalced with fqdn
    pattern: "{prefix}.{fqdn}"
# Maximium idle connections to carbonzipper
idleConnections: 10
pidFile: "/var/run/carbonapi/carbonapi.pid"
# See https://github.com/go-graphite/carbonzipper/blob/master/example.conf#L70-L108 for format explanation
upstreams:
    # Number of 100ms buckets to track request distribution in. Used to build
    # 'carbon.zipper.hostname.requests_in_0ms_to_100ms' metric and friends.
    # Requests beyond the last bucket are logged as slow
    # (default of 10 implies "slow" is >1 second).
    buckets: 10

    timeouts:
        # Maximum total backend requesting timeout in ms.
        # ( How long we may spend making requests. )
        global: "10s"
        # Timeout, in ms, once the final backend has been contacted.
        # ( [Effectively] How long we'll wait for the slowest response. )
        afterStarted: "2s"
        # Timeout to connect to the server
        connect: "200ms"

    # Number of concurrent requests to any given backend - default is no limit.
    # If set, you likely want >= MaxIdleConnsPerHost
    concurrencyLimit: 0

    # Configures how often keep alive packets will be sent out
    keepAliveInterval: "30s"

    # Control http.MaxIdleConnsPerHost. Large values can lead to more idle
    # connections on the backend servers which may bump into limits; tune with care.
    maxIdleConnsPerHost: 100

    # "http://host:port" array of instances of carbonserver stores
    # This is the *ONLY* config element in this section that MUST be specified.
#    backends:
#        - "http://127.0.0.1:9090"

    backendsv2:
        backends:
          -
            groupName: "xxx"
            protocol: "carbonapi_v3_pb"
            lbMethod: "broadcast"
            maxTries: 3
            keepAliveInterval: "10s"
            maxIdleConnsPerHost: 100
            timeouts:
                find: "10s"
                render: "60s"
                connect: "200ms"
            servers:
                - "http://127.0.0.1:9090"

    maxGlobs: 0

    #carbonsearch:
        # Instance of carbonsearch backend
    #    backend: "http://127.0.0.1:8070"
        # carbonsearch prefix to reserve/register
    #    prefix: "virt.v1.*"

    # Enable compatibility with graphite-web 0.9
    # This will affect graphite-web 1.0+ with multiple cluster_servers
    # Default: disabled
    graphite09compat: false
# If not zero, enabled cache for find requests
# This parameter controls when it will expire (in seconds)
# Default: 600 (10 minutes)
#graphTemplates: /etc/graphTemplates.example.yaml
expireDelaySec: 10
# Uncomment this to get the behavior of graphite-web as proposed in https://github.com/graphite-project/graphite-web/pull/2239
# Beware this will make darkbackground graphs less readable
#defaultColors:
#      "red": "ff0000"
#      "green": "00ff00"
#      "blue": "#0000ff"
#      "darkred": "#c80032"
#      "darkgreen": "00c800"
#      "darkblue": "002173"
logger:
    - logger: ""
      file: "/var/log/carbonapi/carbonapi.log"
      level: "fatal"
      encoding: "console"
      encodingTime: "iso8601"
      encodingDuration: "seconds"
```

**Simplified query (if applicable)**

```
/render?target=diffSeries(transformNull(diffSeries(sumSeries(metric.path.and.name.cut),+movingAverage(sumSeries(metric.path.and.name.cut),+%221h%22)),+0),+movingMax(movingAverage(transformNull(removeBelowValue(sumSeries(metric.path.and.name.cut),+0.5),+0.5),+%2224h%22),+%2224h%22))&from=-1h&format=json
```

**Backend response (if possible)**

No graphite-clickhouse response.

**Additional context**
Add any other context about the problem here. Like version of a backend.

Graphite-clickhouse 0.12 from master.

**Comment by Civil** [comment]
What carbonapi version do you run? Does that happens in latest stable or current master as well?

For the "Simplified query". That issue is not reproducible even if you start to remove any of the functions?

For the "Backend response" you've mentioned that "No graphite-clickhouse response", however it is not possible that this issue would happen when backend won't reply (as evaluator won't try to apply any functions on empty response and you would get Error 500 instead).

**Comment by Secathor** [comment]
It is carbonapi 0.14.1-1 from deb package.

Pure, clean metic works instantly.. so there is probably mistake in this query.

Will check again :)

**Comment by Felixoid** [comment]
Maybe, it's fixed in https://github.com/go-graphite/carbonapi/pull/529

Somehow the query looks a little bit related to the fix

**Comment by Civil** [comment]
Well, 'panic' should never occur. At all.

Could you please try any version that have a PR #529 merged? (e.x. current master) As there is a high chance that it was fixed there but I just haven't tagged a release yet (I want to make config handling more intuitive before releasing 0.14.2)

**Comment by Secathor** [comment]
Hey. Cloned current master, installed go-1.14 and cairo dependencies.. package was compiled:

"build_version": "0.14.1-21-g5538"

But it doesn't fix the issue :(

Stack trace is a little different now:

```
Internal Server Error: runtime error: index out of range [60] with length 60
Stack trace: github.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler.func2
	/root/tmp/carbonapi/cmd/carbonapi/http/render_handler.go:238
runtime.gopanic
	/usr/lib/go-1.14/src/runtime/panic.go:975
runtime.goPanicIndex
	/usr/lib/go-1.14/src/runtime/panic.go:88
github.com/go-graphite/carbonapi/expr/helper.AggregateSeries
	/root/tmp/carbonapi/expr/helper/helper.go:153
github.com/go-graphite/carbonapi/expr/functions/aggregate.(*aggregate).Do
	/root/tmp/carbonapi/expr/functions/aggregate/function.go:79
github.com/go-graphite/carbonapi/expr.EvalExpr
	/root/tmp/carbonapi/expr/expr.go:153
github.com/go-graphite/carbonapi/expr.evaluator.Eval
	/root/tmp/carbonapi/expr/expr.go:119
github.com/go-graphite/carbonapi/expr/helper.GetSeriesArg
	/root/tmp/carbonapi/expr/helper/helper.go:41
github.com/go-graphite/carbonapi/expr/functions/transformNull.(*transformNull).Do
	/root/tmp/carbonapi/expr/functions/transformNull/function.go:34
github.com/go-graphite/carbonapi/expr.EvalExpr
	/root/tmp/carbonapi/expr/expr.go:153
github.com/go-graphite/carbonapi/expr.evaluator.Eval
	/root/tmp/carbonapi/expr/expr.go:119
github.com/go-graphite/carbonapi/expr/helper.GetSeriesArg
	/root/tmp/carbonapi/expr/helper/helper.go:41
github.com/go-graphite/carbonapi/expr/helper.GetSeriesArgs
	/root/tmp/carbonapi/expr/helper/helper.go:64
github.com/go-graphite/carbonapi/expr/helper.GetSeriesArgsAndRemoveNonExisting
	/root/tmp/carbonapi/expr/helper/helper.go:81
github.com/go-graphite/carbonapi/expr/functions/aggregate.(*aggregate).Do
	/root/tmp/carbonapi/expr/functions/aggregate/function.go:48
github.com/go-graphite/carbonapi/expr.EvalExpr
	/root/tmp/carbonapi/expr/expr.go:153
github.com/go-graphite/carbonapi/expr.evaluator.Eval
	/root/tmp/carbonapi/expr/expr.go:119
github.com/go-graphite/carbonapi/expr.evaluator.FetchAndEvalExp
	/root/tmp/carbonapi/expr/expr.go:96
github.com/go-graphite/carbonapi/expr.FetchAndEvalExp
	/root/tmp/carbonapi/expr/expr.go:131
github.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler
	/root/tmp/carbonapi/cmd/carbonapi/http/render_handler.go:267
net/http.HandlerFunc.ServeHTTP
	/usr/lib/go-1.14/src/net/http/server.go:2041
github.com/go-graphite/carbonapi/util/ctx.ParseCtx.func1
	/root/tmp/carbonapi/util/ctx/ctx.go:90
github.com/go-graphite/carbonapi/cmd/carbonapi/http.enrichContextWithHeaders.func1
	/root/tmp/carbonapi/cmd/carbonapi/http/enrichcontext.go:32
github.com/dgryski/httputil.TimeHandler.func1
	/root/tmp/carbonapi/vendor/github.com/dgryski/httputil/times.go:26
github.com/dgryski/httputil.TrackConnections.func1
	/root/tmp/carbonapi/vendor/github.com/dgryski/httputil/track.go:40
net/http.HandlerFunc.ServeHTTP
	/usr/lib/go-1.14/src/net/http/server.go:2041
net/http.(*ServeMux).ServeHTTP
	/usr/lib/go-1.14/src/net/http/server.go:2416
github.com/gorilla/handlers.CompressHandlerLevel.func1
	/root/tmp/carbonapi/vendor/github.com/gorilla/handlers/compress.go:148
net/http.HandlerFunc.ServeHTTP
	/usr/lib/go-1.14/src/net/http/server.go:2041
github.com/gorilla/handlers.(*cors).ServeHTTP
	/root/tmp/carbonapi/vendor/github.com/gorilla/handlers/cors.go:54
github.com/gorilla/handlers.ProxyHeaders.func1
	/root/tmp/carbonapi/vendor/github.com/gorilla/handlers/proxy_headers.go:59
net/http.HandlerFunc.ServeHTTP
	/usr/lib/go-1.14/src/net/http/server.go:2041
net/http.serverHandler.ServeHTTP
	/usr/lib/go-1.14/src/net/http/server.go:2836
net/http.(*conn).serve
	/usr/lib/go-1.14/src/net/http/server.go:1924
```

**Comment by Secathor** [comment]
OK, found "issue" in query:

This below has issue:

```
/render?target=movingMax(movingAverage(transformNull(removeBelowValue(sumSeries(some.metric.*.something),+0.5),+0.5),+%2224h%22))&from=-10m&format=json"
```

Removing "movingMax" function "fixing" it and I am able to get json with datapoints.

This below is fine:

```
/render?target=movingAverage(transformNull(removeBelowValue(sumSeries(some.metric.*.something),+0.5),+0.5),+%2224h%22)&from=-10m&format=json
```

Also, problem occurs when I even want to use movingMax alone:

```
/render?target=movingMax(some.metric.*.something)&from=-10m&format=json"
```

COMPATIBILITY.md says, that syntax is:

```
movingMax(seriesList, windowSize, xFilesFactor=None)
```

So when I put:

```
/render?target=movingMax(some.metric.*.something,10)&from=-10m&format=json
```

Issue no longer exist and the 1st, big query also is fine then.

The query which works:

```
/render?target=diffSeries(transformNull(diffSeries(sumSeries(some.metric.*.something),+movingAverage(sumSeries(some.metric.*.something),+%221h%22)),+0),+movingMax(movingAverage(transformNull(removeBelowValue(sumSeries(some.metric.*.something),+0.5),+0.5),+%2224h%22),10,+%2224h%22))&from=-1h&format=json
```

You guys should be able to repeat this error just using movingMax on any metrics without additional parameter, like for example clickhouse internal metrics:

This below cases panic also, you may try on your setups:

```
/render?target=movingMax(internal.one_min.*.ClickHouse.Metrics.GlobalThread)
```

**Comment by Secathor** [comment]
Actually all "moving" functions:

```

movingAverage(seriesList, windowSize, xFilesFactor=None)
movingMax(seriesList, windowSize, xFilesFactor=None) 
movingMedian(seriesList, windowSize, xFilesFactor=None) 
movingMin(seriesList, windowSize, xFilesFactor=None) 
movingSum(seriesList, windowSize, xFilesFactor=None) 
```

Without 2nd argument (windowSize), cause panic on my setup.

**Comment by Felixoid** [comment]
Hmm, according to https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.movingMin, windowSize is a mandatory argument. And according to COMPATIBILITY.md too.

The error should be much more descriptive, for sure. But functions behave properly, I'd say.

**Comment by Secathor** [comment]
Yes, I guess it's not a bug as is. I think we can close this ticket, the issue appear when there is no windowSize argument in "moving*" function.

**Comment by Civil** [comment]
It's still a bug as the 2nd argument still must be made mandatory.

**Comment by Secathor** [comment]
I have new update, I was checking it all again to summarize everything, and I found that issue is again not that ambiguous.

First query is fine, second one causes panic :( Only change is 1min vs 2min on last argument.

```
/render?target=diffSeries(transformNull(diffSeries(sumSeries(some.metric.*.something),+movingAverage(sumSeries(some.metric.*.something),+%221h%22)),+0),+movingMax(movingAverage(transformNull(removeBelowValue(sumSeries(some.metric.*.something),+0.5),+0.5),+%2224h%22),+%221min%22))&from=-1h&format=json"
```


```
/render?target=diffSeries(transformNull(diffSeries(sumSeries(some.metric.*.something),+movingAverage(sumSeries(some.metric.*.something),+%221h%22)),+0),+movingMax(movingAverage(transformNull(removeBelowValue(sumSeries(some.metric.*.something),+0.5),+0.5),+%2224h%22),+%222min%22))&from=-1h&format=json"
```

No logs in graphite-clickhouse, it's not "metrics limit exceeded"..

**Comment by Felixoid** [comment]
to me, it looks like another issue. The least reproducing query is `/render?target=diffSeries(sumSeries(metric),+movingAverage(sumSeries(metric),+%221h%22))&from=-30m&format=json`

And the issue here is around aligning metrics, I'd say

```
Internal Server Error: runtime error: index out of range [30] with length 30
Stack trace: github.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler.func2
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/cmd/carbonapi/http/render_handler.go:238
runtime.gopanic
        /usr/lib/go/src/runtime/panic.go:975
runtime.goPanicIndex
        /usr/lib/go/src/runtime/panic.go:88
github.com/go-graphite/carbonapi/expr/helper.AggregateSeries
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/expr/helper/helper.go:153
github.com/go-graphite/carbonapi/expr/functions/aggregate.(*aggregate).Do
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/expr/functions/aggregate/function.go:79
github.com/go-graphite/carbonapi/expr.EvalExpr
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/expr/expr.go:153
github.com/go-graphite/carbonapi/expr.evaluator.Eval
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/expr/expr.go:119
github.com/go-graphite/carbonapi/expr.evaluator.FetchAndEvalExp
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/expr/expr.go:96
github.com/go-graphite/carbonapi/expr.FetchAndEvalExp
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/expr/expr.go:131
github.com/go-graphite/carbonapi/cmd/carbonapi/http.renderHandler
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/cmd/carbonapi/http/render_handler.go:267
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2042
github.com/go-graphite/carbonapi/util/ctx.ParseCtx.func1
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/util/ctx/ctx.go:90
github.com/go-graphite/carbonapi/cmd/carbonapi/http.enrichContextWithHeaders.func1
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/cmd/carbonapi/http/enrichcontext.go:32
github.com/dgryski/httputil.TimeHandler.func1
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/vendor/github.com/dgryski/httputil/times.go:26
github.com/dgryski/httputil.TrackConnections.func1
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/vendor/github.com/dgryski/httputil/track.go:40
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2042
net/http.(*ServeMux).ServeHTTP
        /usr/lib/go/src/net/http/server.go:2417
github.com/gorilla/handlers.CompressHandlerLevel.func1
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/compress.go:148
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2042
github.com/gorilla/handlers.(*cors).ServeHTTP
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/cors.go:54
github.com/gorilla/handlers.ProxyHeaders.func1
        /home/felixoid/OPT/Felixoid/github/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/proxy_headers.go:59
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2042
net/http.serverHandler.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2843
net/http.(*conn).serve
        /usr/lib/go/src/net/http/server.go:1925
```

**Comment by Secathor** [comment]
Yes, it's different one for sure. I hope I didn't create too much confusion here.

**Comment by Felixoid** [comment]
But it seems related to `moving*` still. The function creates the request to backends with extra points for `windowSize`, but then adjust it to the global `from/until`. It keeps the extra values as NaN though. So, it's a `moving*` bug still

**Comment by Felixoid** [comment]
@Secathor could you try the fix from linked PR, please?

**Comment by Secathor** [comment]
@Felixoid Hi :) Yes, it fixes all my issues, problematic metrics (I actually had two of them), are now served 100% properly :-)

**Comment by Felixoid** [comment]
The branch is still a little bit buggy, so I'll adjust it properly, e.g. StartTime, StopTime, and the number of values must be calculated properly. So, don't yet use it in production, please :-j

**Comment by Secathor** [comment]
Please ping me when it is 100% ready, I am testing it right now, issues with unsupported queries are 100% non-existent now.
